services:
  rcron:
    image: ${RCRON_IMAGE:-ghcr.io/shahram7/rcron:latest}
    ports:
      - "8000:8000"
    environment:
      TZ: ${TZ:-UTC}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER:-}
      BASIC_AUTH_PWD: ${BASIC_AUTH_PWD:-}
    volumes:
      - rclone-config:/config
      - rcron-data:/rcron-data
    restart: unless-stopped

volumes:
  rclone-config:
  rcron-data: