[supervisord]
nodaemon=true
logfile=/var/log/rcron/supervisord.log
pidfile=/tmp/supervisord.pid

[program:cron]
command=/usr/sbin/crond -l 2 -f -c %(ENV_CRON_PATH)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:crontab-ui]
directory=/crontab-ui
command=/usr/bin/node /crontab-ui/app.js
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
